title: ISMIR 2022
logo: /assets/img/ismir2022.png
description: International Society for Music Information Retrieval Conference 2022, Bengaluru, India
domain: "ismir2022.ismir.net"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
