title: ISMIR 2022
logo: /assets/img/ismir2022.png
description: International Society for Music Information Retrieval Conference 2022, Bengaluru, India
theme: jekyll-theme-minimal
domain: "ismir2022.ismir.net"
